apiVersion: v1
kind: Service
metadata:
  name: cloudground-nodejs-service
  labels:
    name: cloudground-nodejs
spec:
  type: LoadBalancer
  ports:
  - port: 8070
    targetPort: 8070
  selector:
    app: cloudground-nodejs