# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-go:
    docker:
      # specify the version
      - image: circleci/golang:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/Cloudground/Cloudground
    steps:
      - checkout
      - run: |
          mkdir -p /tmp/output
          go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Prepare Go wrapper
          working_directory: go/src/Cloudground
          command: |
            chmod +x gow.sh
      - run:
          name: Run Go dep
          working_directory: go/src/Cloudground
          command: |
            ./gow.sh dep ensure
      - run:
          name: Build
          working_directory: go/src/Cloudground
          command: |
            ./gow.sh go build  -o /tmp/output/Cloudground
#      - run: go get -v -t -d ./...
#      - run: go test -v ./...
      - persist_to_workspace:
          root: /tmp/output
          paths:
            - Cloudground

  build-nodejs:
    docker:
      - image: circleci/node:8
    working_directory: ~/Cloudground
    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "nodejs/package.json" }}
          - dependencies-

      - run:
          working_directory: nodejs
          command: |
            npm install
      - save_cache:
          paths:
            - nodejs/node_modules
          key: dependencies-{{ checksum "nodejs/package.json" }}
#      - run:
#          working_directory: nodejs
#          command: yarn ci

#      - persist_to_workspace:
#          root: ~/Cloudground/nodejs/dist
#          paths:
#            - index.html
#            - assets/*


workflows:
  version: 2

  ci:
    jobs:
      - build-go
      - build-nodejs
#      - package:
#          requires:
#            - build-go
#            - build-nodejs

ship-it:
    jobs:
      - build-go:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build-node:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/