apiVersion: v1
kind: Service
metadata:
  name: cloudground-go-service
  labels:
    name: cloudground-go
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: cloudground-go