apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: mongo-volume-${INSTANCE}
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  hostPath:
    path: "/mnt/data/mongo-${INSTANCE}"