apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    name: mongo-express
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: mongo-express